### ISSUE TITLE
Issues with isset function

### ISSUE THREAD

**Issue by quanyang** [ircmaxell/php-cfg#9] opened 2016-02-24 18:17 UTC
Currently the CFG is showing isset as:

```
    Expr_Isset
        result: Var#9
```

However, this would not give information on what is being checked by the isset function.

Not sure if this would be considered an issue to you guys, but I kind of solved it by changing isset to an operand instead of block.

**Comment by nikic** [comment] 2016-02-24 22:42
Fixed with https://github.com/ircmaxell/php-cfg/commit/741a668a935cc198f543c18a6310fcfc62a394cd by using a vars subnode, which is an array of variables that are checked.

In the future we should instread define `Expr\Isset_` to be single-argument and desugar multi-arg issets into single-arg ones combined via `&&` operations. However issue #10 should be fixed before doing that.

**Closed by nikic** 2016-02-24 22:42 UTC

**Comment by quanyang** [comment] 2016-02-25 15:12
Same issue with empty function and maybe others.

**Comment by nikic** [comment] 2016-02-25 15:23
@quanyang Fixed to use operand in https://github.com/ircmaxell/php-cfg/commit/1744d0ba3b98b97a9644216ec2ca68d84a78e689.

The fact that it was done the same way there makes me think that it was intentional. Maybe this was intended as some weird way to handle the fact that these uses do not generate notices...

**Comment by quanyang** [comment] 2016-02-25 15:29
@nikic hmm the AST generated by PHP-Parser does show the parameter variable.

You might be right that it could be intended, however I'm looking at performing some further analysis using the CFG generated by php-cfg, and these information could be crucial.

Anyway thanks for fixing!
